### ISSUE TITLE
Media Modal: Gallery Tab

### ISSUE THREAD

**Issue by landwire** [buddypress/bp-attachments#10]
Hi there,

would be great if you could also have the option to show the gallery tab in the media modal, so that a user can choose from his existing pictures for the avatar and does not need to upload a new image all the time.

Thanks,
Sascha

**Comment by imath** [comment]
Hello Sascha,

Thanks for your interest and feedback about this plugin. The way it is built, objects are very different from a regular attachments. I can understand the need for a user having a role enabling him to upload media on his post/pages, but for regular users who shouldn't have the upload capability i think all media would be "BuddyPress attachements"

**Comment by imath** [comment]
Hi, sorry I haven't updated this repository for a while, I'm going to close this issue because I will completely rewrite this plugin so that it enjoys latest WordPress and BuddyPress improvements.
