### ISSUE TITLE
Code Question: How and where is the old avatar uploader replaced?

### ISSUE THREAD

**Issue by landwire** [buddypress/bp-attachments#11]
How and where in the code is the existing avatar template replaced in the bp-attachments plugin? I have one install where despite activating the plugin and activating the component the old version of the avatar upload is still showing. I am trying to find out why that could be, without having to switch off all my plugins. Maybe I am just missing a crucial hook in my BP template files?

On a clean install it works fine.
Ok, it throws a javascript error:
`Uncaught TypeError: Cannot read property 'title' of undefined media-editor.js?ver=1.0.0-bleeding:535(anonymous function) media-editor.js?ver=1.0.0-bleeding:535(anonymous function) media-editor.js?ver=1.0.0-bleeding:1442`

Not sure why that could be. Any ideas?
Thanks for any help,
Sascha

**Comment by imath** [comment]
Thanks for your feedback. I will check this as soon as i can.

**Comment by imath** [comment]
Hi, sorry I haven't updated this repository for a while, I'm going to close this issue because I will completely rewrite this plugin so that it enjoys latest WordPress and BuddyPress improvements.
