### ISSUE TITLE
Conflict with wp_enqueue_media()

### ISSUE THREAD

**Issue by landwire** [buddypress/bp-attachments#12]
Hello imath,

I am getting a JS error ("Uncaught TypeError: Cannot read property 'add' of undefined") with the new Buddypress Attachments API when I am loading media scripts with wp_enqueue_media() on the same page as the attachments upload.
Could you confirm this conflict? What can be done about it?
I used the 2014 theme.

This is related to ticket 11, but I thought I open a new one as the title of 11 is somewhat misleading...
Thanks for the great work on the BP Attachments API btw!

You can see the error in the console on: http://www.landwire.net/members/sascha/profile/change-avatar/
But you need to log in. If you want log in data, just let me know. But I am sure you can recreate the error on a clean install.

I guess there is some code in bp-plupload, that conflicts with the scripts enqueued by wp_enqueue_media().

**Comment by landwire** [comment]
I also installed an absolute clean new install just to make sure and it does the same:

http://clean.landwire.net/members/imath/profile/change-avatar/

Just log in with username "imath" and password "imath"
Should I post this to the BuddyPress Trac?

**Comment by imath** [comment]
Let me look at this today before, please.

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
What version of BuddyPress do you use ? Because, there's a conflict with BuddyPress 2.3 i need to fix.

**Comment by imath** [comment]
@landwire Oh but you're not talking about this plugin actually !! You're talking about the BP Attachments API. Then yes you should open a ticket on BuddyPress trac, i understand why this is happening, but i wonder why you would enqueue WordPress media in the change avatar templates ???

**Comment by landwire** [comment]
Yes, sorry! I just was not sure where to post it.

I have included some functionality to have a cover image on the profile (in addition to the avatar image), I guess like Facebook does.
That's why I need to enqueue the WP media scripts.

If you know why this is happening, do you also know how to fix it?

I'll post it in trac tonight.
Thanks for the quick reply!

Von unterwegs geschickt

**Comment by imath** [comment]
Yeah, it's a namespace conflict. I think i have a patch ready, so you'll be able to test it. I'll attach it to the ticket once it's created.

Btw, fwiw 
1) https://buddypress.trac.wordpress.org/ticket/6570
2) You should use the BuddyPress Attachments API :)
3) You should use a specific user's profile sub nav to avoid loading media or Attachments scripts on each page of the user's profile.

**Comment by landwire** [comment]
Thanks for the info! So I wait until this is implemented the correct way in BuddyPress. I did the Cover image functionality before I knew about the attachments API! You are right about the script loading, but I am not a big fan of sub nav. I like it when a user just clicks an icon and a modal (or similar) opens with the image upload options and then on close, the modal closes and the content on tha page gets updates with AJAX. That's always what I prefer at least. I also wanted people to choose from their already uploaded images, which I can do with the WP media scripts. No idea if I can use the Attachments API to do that too...
I'll post the ticket now regardless. I am sure there are use cases where someone needs to enqueue the WP Media Scripts and that should not collide with the Attachments API.
Thanks again,
Sascha

**Comment by imath** [comment]
> I am sure there are use cases where someone needs to enqueue the WP Media Scripts and that should not collide with the Attachments API.

Absolutely, i have a patch ready, waiting for your ticket :)

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
The discussion will continue there https://buddypress.trac.wordpress.org/ticket/6574
