### ISSUE TITLE
Attached images are not displayed in wp-admin Activity edit screen

### ISSUE THREAD

**Issue by slaFFik** [buddypress/bp-attachments#17]
When you open an associated with a blog post activity item - it has both excerpt and a featured image. While images attached using this plugin for ordinary status updates are not displayed there.
It's not fair :)

**Comment by imath** [comment]
Thanks for your feedback!! That's because i'm not using the content of the activity. Good catch!! Will look at it asap :)

**Comment by slaFFik** [comment]
Also on this page `/wp-admin/admin.php?page=bp-activity` cover_added (why cover?) is displayed separately from the associated activity item.
Also it displays that this is an unregistered event.

**Comment by imath** [comment]
I think there's another plugin that is involved there! I'm not using these words (cover, cover_added) at all ;)
Just rechecked by searching it in all files of the plugin.

"Unregistered event" how a regular update can be unregistered ??

It's a photo attached to an 'activity_update', it's not a new type of activity ;)

imath.
http://profiles.wordpress.org/imath/

**Comment by slaFFik** [comment]
Yeah, you are right regarding cover. Completely forgot about the other plugin. Sorry!

**Comment by imath** [comment]
No problem. After a first look about adding the photo into the activity Administration screen, i can say it's not easy! 

The BP Activity Admin List Table should be improved:
- always pass the $item in all column method filters
- include a default column method

And i need to improve a function of the Attachments API

So your feedback is really helpful ;) Thanks again.

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
Ok in BP Activity List Table you should now see : 
![list](https://cloud.githubusercontent.com/assets/1834524/9647630/a04f4094-51df-11e5-902a-6b74190b8c4a.png)

And in the Screen to edit a single activity you should see.
![edit](https://cloud.githubusercontent.com/assets/1834524/9647673/eb423a3e-51df-11e5-8435-9e3ccc37e4af.png)

**Comment by imath** [comment]
we'll need to add moderation tools in the future

**Comment by slaFFik** [comment]
Awesome! Just checked on own site.

BTW, I think moderation should be a separate task, not part of this, I suppose.

**Comment by imath** [comment]
Ok then i'll open a new ticket :)
Thanks for your feedback

imath.
http://profiles.wordpress.org/imath/

**Comment by imath** [comment]
#22 will take care of moderating tools as suggested.
