### ISSUE TITLE
missing sprint and doubled string

### ISSUE THREAD

**Issue by chouf1** [buddypress/bp-attachments#21]
We have two same error msg in 2 version because of a dot.
Remove or add one and see also sprintf difference. IMO it's missing.

`bp-attachments\bp-attachments-screens.php:**89** bp_core_add_message( sprintf( __( 'Attachment could not be edited', 'bp-attachments' ), 'error' ) );`

`bp-attachments\bp-attachments-screens.php:**99** bp_core_add_message( __( 'Attachment could not be edited.', 'bp-attachments' ), 'error' );`

**Comment by imath** [comment]
good catch :)
