### ISSUE TITLE
File types bug

### ISSUE THREAD

**Issue by ryanhellyer** [buddypress/bp-attachments#23]
The plugin is not allowing me to upload non-standard file types, despite having enabled them in WordPress. I can upload the extra file types elsewhere (media uploader for example), but not via the BP Attachments plugin. Regular file types, like PNG, JPG etc. work fine.

```
test.pdf: Sorry, this file type is not permitted for security reasons.
```

**Comment by imath** [comment]
Hi, sorry I haven't updated this repository for a while, I'm going to close this issue because I will completely rewrite this plugin so that it enjoys latest WordPress and BuddyPress improvements.
