### ISSUE TITLE
Let's rewrite completely the plugin

### ISSUE THREAD

**Issue by imath** [buddypress/bp-attachments#27]
FYI, I'm going to work actively on the plugin with a completely different approach.

- Use React and take advantage of the WordPress packages introduced by the Gutenberg Project,
- Use the BP REST API,
- Stop using a Custom Post Type to use instead a more direct management within the file system.

**Comment by vince5959** [comment]
Hi, is the plugin currently operational and stable with the new version of bbpress?
Thank you very much for your great work. :) :) :) :) 
Vince

**Comment by imath** [comment]
Hi Vince, it’s still a WIP. I hope to work back on it asap.

**Comment by Florent73** [comment]
Hi!

And this plugin is over : https://github.com/buddypress/bp-attachments ?

It don't works actually...

A another solution?

Thanks

**Comment by imath** [comment]
Hi, if you're talking of the state of the plugin before I began rewriting it, you can still get it there: https://github.com/buddypress/bp-attachments/tree/1.2

For the rewrote version, it's still WIP.

**Comment by Florent73** [comment]
Hi!

Thanks for that, but it's not for BuddyPress Messages?

How do it? I would like a upload attachment for my message (like picture).

Thanks
![Capture d'écran 2020-05-18 17 59 22](https://user-images.githubusercontent.com/927331/82234326-92966b00-9931-11ea-8cc6-35fb978d20f5.png)
