### ISSUE TITLE
Question about the private directory permission

### ISSUE THREAD

**Issue by Natchoice** [buddypress/bp-attachments#53]
Getting this error message in the backend. What are the permission needed? The root is set properly.

The private root directory is not set the right way.
The /chroot/home/cfrli/site.com/buddypress-private 
directory needs be owned by "cfrli".

**Comment by imath** [comment]
Hi @Natchoice 

Thanks for testing the plugin and for your feedback. According to the error you got you need to:
`sudo chown -R cfrli /chroot/home/cfrli/site.com/buddypress-private`

**Comment by Natchoice** [comment]
Thanks for the reply didn’t know if this was the place to post questions
