### ISSUE TITLE
Should `bp_attachments_get_src()` use `bp_attachments_uploads_dir_get()` instead of `bp_upload_dir()` ?

### ISSUE THREAD

**Issue by imath** [buddypress/bp-attachments#60]
See: https://wordpress.org/support/topic/bp_attachments_get_src-usues-wrong-function/

**Comment by shawfactor** [comment]
It definitely should, at the moment the situation is inconsistent so if you filter one then problems occur (and being able to filter the attachments directory is useful)

**Comment by shawfactor** [comment]
Imath there are other places where bp_upload_dir() is used, Ive not looked at the impact but it likely needs to be changed elsewhere in the plugin for consistency.
